## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

#### Import numpy

In [1]:
import numpy as np

#### Produce 2 vectors

In [2]:
a1 = np.arange(5,11)
a2 = np.arange(15,21)

print('a1 = ', a1)
print('\na2 = ', a2)

a1 =  [ 5  6  7  8  9 10]

a2 =  [15 16 17 18 19 20]


## Without numpy

#### Computing outer product of 2 vectors (non-numpy way)

In [3]:
outer_product = []
for i in range(len(a1)):
    row = []
    for j in range(len(a2)):
        row.append(a1[i] * a2[j])
    outer_product.append(row)


print('outer product = ')
outer_product

outer product = 


[[75, 80, 85, 90, 95, 100],
 [90, 96, 102, 108, 114, 120],
 [105, 112, 119, 126, 133, 140],
 [120, 128, 136, 144, 152, 160],
 [135, 144, 153, 162, 171, 180],
 [150, 160, 170, 180, 190, 200]]

#### Computing trace of resulting matrix (non-numpy way):

In [4]:
list(outer_product)

[[75, 80, 85, 90, 95, 100],
 [90, 96, 102, 108, 114, 120],
 [105, 112, 119, 126, 133, 140],
 [120, 128, 136, 144, 152, 160],
 [135, 144, 153, 162, 171, 180],
 [150, 160, 170, 180, 190, 200]]

In [5]:
trace_array = []

for i in range(len(outer_product)):
    trace_array.append(outer_product[i][i])

print('Diagonal Array =', trace_array)
print('Trace = ', sum(trace_array))

Diagonal Array = [75, 96, 119, 144, 171, 200]
Trace =  805


## With numpy

In [6]:
outer_product_np = np.outer(a1,a2)
print('Outer Product using numpy: \n\n', outer_product_np)

Outer Product using numpy: 

 [[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]


In [7]:
trace_array_np = outer_product_np.diagonal()

print('Diagonal array using numpy: ', trace_array_np)
print('Trace = ', trace_array_np.sum())

Diagonal array using numpy:  [ 75  96 119 144 171 200]
Trace =  805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

#### Make two matricies

In [20]:
rand1 = (np.random.rand(4,3)*10)
rand2 = (np.random.rand(3,4)*10)
rand1 = rand1.astype(int)
rand2 = rand2.astype(int)

print('A = \n', rand1)
print('\nB = \n', rand2)

A = 
 [[0 3 3]
 [7 6 9]
 [1 8 4]
 [1 1 1]]

B = 
 [[9 8 6 3]
 [3 4 5 1]
 [7 0 8 8]]


#### Dot product using contentional for-loop

In [21]:
result = [] 
for i in range(len(rand1)):

    row = [] 
    for j in range(len(rand2[0])):

        product = 0 
        for v in range(len(rand1[i])):
            product += rand1[i][v] * rand2[v][j]
        row.append(product) 

    result.append(row)


print(result)

[[30, 12, 39, 27], [144, 80, 144, 99], [61, 40, 78, 43], [19, 12, 19, 12]]


#### List Comprehension

In [ ]:
list_comprehension = [rand1[i][v] * rand2[v][j] for v in range(len(rand1[i])) ]

In [33]:
list_comprehension = [rand1[i][v] * rand2[v][j] for v in range(len(rand1[i])) for j in range(len(rand2[0])) for i in range(len(rand1))]
print('Dot Product: ', list_comprehension)

Dot Product:  [0, 63, 9, 9, 0, 56, 8, 8, 0, 42, 6, 6, 0, 21, 3, 3, 9, 18, 24, 3, 12, 24, 32, 4, 15, 30, 40, 5, 3, 6, 8, 1, 21, 63, 28, 7, 0, 0, 0, 0, 24, 72, 32, 8, 24, 72, 32, 8]


In [29]:
range(len(rand1))

range(0, 4)

#### Dot product using numpy

In [24]:
dot_product_np = np.dot(rand1, rand2)
print('Dot product using numpy =\n\n', dot_product_np)

Dot product using numpy =

 [[ 30  12  39  27]
 [144  80 144  99]
 [ 61  40  78  43]
 [ 19  12  19  12]]


### Fancy Indexing

In [25]:
fancy_matrix = dot_product_np[[0,1]][:,[2,3]]

In [26]:
diagonal_zeros = fancy_matrix.copy()

for i in range(len(diagonal_zeros)):
    diagonal_zeros[i,i] = 0
    
print(diagonal_zeros)    

[[  0  27]
 [144   0]]
